# -*- coding: utf-8 -*-
"""BISECTION ALGORITHM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19C0m7t-7PvrNJ1XunxDKRHymQyu9F4Zy
"""

#############################
#    BISECTION ALGORITHM    #
#############################

def prints(a, b, c, i):
  print("\nIteration [" + str(i + 1) + "]: ")
  print(a, b, c, f(c))

# Main function
''' Declarations & Initialization/Inputs '''
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = (a+b)/2
i = 0

close = float(input("Enter closeness: "))
iter = int(input("How many iterations? "))

# Function input
x = input('Enter the function: ')
exec('def f(x): return (' + x + ')')
res_a = f(a)
res_b = f(b)
res_c = f(c)

if res_a < 0 and res_b > 0:
    while res_a < 0 and res_b > 0 and abs(res_c) > close and i < iter:
      c = (a+b)/2
      if res_c < 0:
        a = c
      elif res_c > 0:
        b = c
      prints(a, b, c, i)
      i = i + 1

elif (res_a > 0 and res_b > 0) or (res_a < 0 and res_b < 0):
    print("\nError! Cannot process these values. res_a and res_b cannot be both greater than or less than zero.\n")

elif res_a > 0 and res_b < 0:
    while res_a > 0 and res_b < 0 and abs(res_c) > close and i < iter:
      c = (a+b)/2
      if res_c > 0:
        a = c
      elif res_c < 0:
        b = c
      prints(a, b, c, i)
      i = i + 1